name: Periodically build list from AdGuard's repo
on:
  schedule:
    - cron: '0 1 * * *' # Every day at 01:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          git config --global user.name 'Axel Leroy'
          git config --global user.email 'axeleroy@users.noreply.github.com'

          git clone https://github.com/AdguardTeam/cname-trackers.git
          rm blocklist.txt
          for file in cname-trackers/trackers/*.txt; do cat $file >> blocklist.txt; done

          sed -i '/^!/d' blocklist.txt
          sed -i 's/||\(..*\)\^/!*\1/g' blocklist.txt

          git add blocklist.txt
          git commit -m 'Updated blocklist'
          git push
